

services:


  db_updater:
    build: db_updater
    depends_on:
      - db


  api:
    depends_on:
      db_updater:
        condition: service_completed_successfully

  frontend:
    build:
      target: prod
    ports:
      - "443:443"
    volumes:
      - letsencrypt-etc:/etc/letsencrypt:ro
      - letsencrypt-var:/var/lib/letsencrypt:ro


  certbot:
    image: certbot/certbot
    command: "renew --agree-tos -n"
    ports:
      - "80:80"
    volumes:
      - letsencrypt-etc:/etc/letsencrypt:rw
      - letsencrypt-var:/var/lib/letsencrypt:rw



volumes:
  letsencrypt-etc:
  letsencrypt-var:
