services:


  tenant_index:
    build: tenant_index
    volumes:
      - tenantindex_data:/var/lib/postgresql


  db:
    build: db
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql



  api:
    build:
      context: api
      target: dev
    depends_on:
      db:
        condition: service_healthy
        restart: true


  superapi:
    build:
      context: superapi
    depends_on:
      db:
        condition: service_healthy
        restart: true
      tenant_index:
        condition: service_healthy
        restart: true

  frontend:
    build:
      context: frontend
      target: dev
    ports:
      - "80:80"
      - "81:81"
    volumes:
      # Mount the directory from the host, so that edits to the files do not require an image rebuild.
      - ./frontend/content:/usr/share/nginx/html:ro
      - ./frontend/content_tenant_admin:/opt/tenant_admin/html:ro
    depends_on:
      api:
        condition: service_healthy
      superapi:
        condition: service_healthy

volumes:
  tenantindex_data:
  db-data:

