services:

  db:
    expose:
      - 5432
    ports:
      - "5432:5432"



  frontend:
    build:
      target: dev
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./frontend/content:/usr/share/nginx/html:ro
