services:


  db:
    build: db
    volumes:
      - db-data:/var/lib/postgresql


  api:
    build:
      context: api
      target: prod


  frontend:
    build: frontend
    ports:
      - "8000:8000"

volumes:
  db-data:

