services:

  # Update this to the name of the service you want to work with in your docker-compose.yml file
  api:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: [] # https://docs.docker.com/reference/compose-file/services/#entrypoint
    command: sleep infinity

    # Disable the healthcheck, (actually don't disable it, but make it pass immediately)
    # otherwise the container tries to curl itself even before we've started debugging.
    healthcheck:
      start_period: 1m
      start_interval: 1s
      test: "true"
      # That's the bash command "true", which immediately succeeds.