server {

	listen 443 ssl;

	ssl_certificate /etc/letsencrypt/live/bookings.peterpi.org/fullchain.pem;
	ssl_certifcate_key /etc/letsencrypt/live/bookings.peterpi.org/privkey.pem;

	server_name bookings.peterpi.org;

	location / {
		root /usr/share/nginx/html;
	}

	location /api/ {
		proxy_pass http://api:5000;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Prefix $http_x_forwarded_prefix;
	}
}